service: cloudfront-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'} 
  stage: ${opt:stage, 'dev'} 

custom:
  base: ${self:service}-${self:provider.stage}
  apiKey: ${param:apiKey, 'cloudfront-1234567890'}

functions:
  cloudfrontApiFunction:
    handler: src/handlers/index.handler
    name: ${self:custom.base}-function
    memorySize: 512
    timeout: 60
    environment:
      API_KEY: ${self:custom.apiKey}
    url:
      cors:
        allowedOrigins: 
          - '*'
        allowedHeaders:
          - Content-Type
          - Authorization
        allowedMethods:
          - GET
          - POST
        allowCredentials: false
        exposedResponseHeaders:
          - Access-Control-Allow-Headers
        maxAge: 0

resources:
  Resources:
    CloudfrontApiDistribution:
      Type: AWS::CloudFront::Distribution
      Properties: 
        DistributionConfig:
          Comment: ${self:custom.base}-distribution
          Enabled: true
          PriceClass: PriceClass_100
          HttpVersion: http2and3
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
            CachedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachePolicyId: ${param:cachePolicyId}
            OriginRequestPolicyId: ${param:originRequestPolicyId}
            ResponseHeadersPolicyId: ${param:responseHeadersPolicyId}
            Compress: false
            SmoothStreaming: false
            TargetOriginId: lambda-origin
            ViewerProtocolPolicy: https-only
          Origins:
            - Id: lambda-origin
              DomainName: !Select [2, !Split ["/", !GetAtt CloudfrontApiFunctionLambdaFunctionUrl.FunctionUrl]]
              CustomOriginConfig: 
                OriginProtocolPolicy: https-only
                OriginSSLProtocols:
                  - TLSv1.2
                OriginReadTimeout: 60
              OriginCustomHeaders:
                - HeaderName: x-api-key
                  HeaderValue: ${self:custom.apiKey}
              # OriginShield:
              #   Enabled: true
              #   OriginShieldRegion: ${self:provider.region}

  Outputs:
    CloudfrontApiUrl:
      Value: !Sub
        - 'https://${DomainName}/'
        - DomainName: !GetAtt CloudfrontApiDistribution.DomainName