services:
  cloudfront-api-policies: # CloudFront Policies stack
    path: resources/cloudfront

  cloudfront-api: # Lambda Function and CloudFront Distribution stack
    path: services/cloudfront-api
    dependsOn: cloudfront-api-policies # Wait for this service to be deployed
    params: # Add the CloudFront Policies outputs as parameters
      cachePolicyId: ${cloudfront-api-policies.cachePolicyId}
      originRequestPolicyId: ${cloudfront-api-policies.originRequestPolicyId}
      responseHeadersPolicyId: ${cloudfront-api-policies.responseHeadersPolicyId}