service: cloudfront-api-policies
frameworkVersion: '3'

provider:
  name: aws
  region: ${opt:region, 'us-east-1'} 
  stage: ${opt:stage, 'dev'} 

custom:
  base: ${self:service}-${self:provider.stage}

resources:
  Resources:
    CachePolicy:
      Type: AWS::CloudFront::CachePolicy
      Properties: 
        CachePolicyConfig:
          Name: ${self:custom.base}-cache
          MinTTL: 0 # Add your minimum cache expiration time in seconds
          DefaultTTL: 30 # Add your default cache expiration time in seconds
          MaxTTL: 60 # Add your maximum cache expiration time in seconds
          ParametersInCacheKeyAndForwardedToOrigin:
            EnableAcceptEncodingGzip: false # Not working with Gzip compression
            CookiesConfig:
              CookieBehavior: none # Not caching cookies
            HeadersConfig:
              HeaderBehavior: none # Not caching headers
            QueryStringsConfig: 
              QueryStringBehavior: all # Caching all query strings

    OriginRequestPolicy:
      Type: AWS::CloudFront::OriginRequestPolicy
      Properties: 
        OriginRequestPolicyConfig:
          Name: ${self:custom.base}-origin
          CookiesConfig:
            CookieBehavior: all # Passing all cookies to Lambda Function
          HeadersConfig:
            HeaderBehavior: allExcept
            Headers:
              - Host  # Passing all headers except "Host" to Lambda Function
          QueryStringsConfig:
            QueryStringBehavior: all # Passing all query strings to Lambda Function
    
    ResponseHeadersPolicy:
      Type: AWS::CloudFront::ResponseHeadersPolicy
      Properties: 
        ResponseHeadersPolicyConfig:
          Name: ${self:custom.base}-response
          CorsConfig: # Default CORS config for the API
              AccessControlAllowCredentials: false # Change to true to allow cookies
              AccessControlAllowHeaders: 
                Items: # Add your allowed headers in here
                  - Content-Type
              AccessControlAllowMethods: 
                Items: # Add your allowed methods in here
                  - OPTIONS
                  - HEAD
              AccessControlAllowOrigins: 
                Items: # Add your allowed origins in here
                  - '*.serverlessguru.com'
              AccessControlExposeHeaders: null # Add your non-CORS-safelisted headers
              AccessControlMaxAgeSec: 0 # Preflight response cache expiration time
              OriginOverride: false # Change to true to override Lambda CORS settings
  
  Outputs:
    cachePolicyId:
      Value: !Ref CachePolicy
    originRequestPolicyId:
      Value: !Ref OriginRequestPolicy
    responseHeadersPolicyId:
      Value: !Ref ResponseHeadersPolicy