services:
  cloudfront-api-policies:
    path: resources/cloudfront

  cloudfront-api:
    path: services/cloudfront-api
    dependsOn: cloudfront-api-policies
    params:
      cachePolicyId: ${cloudfront-api-policies.cachePolicyId}
      originRequestPolicyId: ${cloudfront-api-policies.originRequestPolicyId}
      responseHeadersPolicyId: ${cloudfront-api-policies.responseHeadersPolicyId}